name: DanC
favicon: null
layout_spectrum: 0.07375022466294467
typography_spectrum: 0.845063948770985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4927635674830526
  lightness: 0.5524075580760837
  saturation: 0.8837929700966924
  rhythmicContrast: 0.8687691485974938
purpose: []
